services:
    app:
        image: node
        volumes:
            - .:/app
        build: .
        restart: always
    redis:
        image: redis
        # For testing: expose the port
        ports:
            - "6379:6379"
        restart: always
